# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Checking.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(496, 563)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_result_Hobi = QtWidgets.QPushButton(self.centralwidget)
        self.btn_result_Hobi.setGeometry(QtCore.QRect(50, 230, 81, 23))
        self.btn_result_Hobi.setObjectName("btn_result_Hobi")
        self.lbl_result_Hobi = QtWidgets.QLabel(self.centralwidget)
        self.lbl_result_Hobi.setGeometry(QtCore.QRect(30, 280, 131, 141))
        self.lbl_result_Hobi.setText("")
        self.lbl_result_Hobi.setObjectName("lbl_result_Hobi")
        self.groupHobiler = QtWidgets.QGroupBox(self.centralwidget)
        self.groupHobiler.setGeometry(QtCore.QRect(10, 30, 171, 141))
        self.groupHobiler.setObjectName("groupHobiler")
        self.layoutWidget = QtWidgets.QWidget(self.groupHobiler)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 30, 151, 87))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.CbSinema = QtWidgets.QCheckBox(self.layoutWidget)
        self.CbSinema.setObjectName("CbSinema")
        self.verticalLayout.addWidget(self.CbSinema)
        self.CbBook = QtWidgets.QCheckBox(self.layoutWidget)
        self.CbBook.setObjectName("CbBook")
        self.verticalLayout.addWidget(self.CbBook)
        self.CbSpor = QtWidgets.QCheckBox(self.layoutWidget)
        self.CbSpor.setObjectName("CbSpor")
        self.verticalLayout.addWidget(self.CbSpor)
        self.grouDersler = QtWidgets.QGroupBox(self.centralwidget)
        self.grouDersler.setGeometry(QtCore.QRect(240, 30, 171, 141))
        self.grouDersler.setObjectName("grouDersler")
        self.layoutWidget_2 = QtWidgets.QWidget(self.grouDersler)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 30, 151, 87))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.CbWebTasarm = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.CbWebTasarm.setObjectName("CbWebTasarm")
        self.verticalLayout_2.addWidget(self.CbWebTasarm)
        self.CbProgramlama = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.CbProgramlama.setObjectName("CbProgramlama")
        self.verticalLayout_2.addWidget(self.CbProgramlama)
        self.CbMatematik = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.CbMatematik.setObjectName("CbMatematik")
        self.verticalLayout_2.addWidget(self.CbMatematik)
        self.btn_result_Ders = QtWidgets.QPushButton(self.centralwidget)
        self.btn_result_Ders.setGeometry(QtCore.QRect(270, 230, 81, 23))
        self.btn_result_Ders.setObjectName("btn_result_Ders")
        self.lbl_result_Ders = QtWidgets.QLabel(self.centralwidget)
        self.lbl_result_Ders.setGeometry(QtCore.QRect(250, 280, 131, 141))
        self.lbl_result_Ders.setText("")
        self.lbl_result_Ders.setObjectName("lbl_result_Ders")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 496, 20))
        self.menubar.setObjectName("menubar")
        self.menuChekingg = QtWidgets.QMenu(self.menubar)
        self.menuChekingg.setObjectName("menuChekingg")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuChekingg.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_result_Hobi.setText(_translate("MainWindow", "Hobileri Onayla"))
        self.groupHobiler.setTitle(_translate("MainWindow", "GroupBox"))
        self.CbSinema.setText(_translate("MainWindow", "Sinema"))
        self.CbBook.setText(_translate("MainWindow", "Kitap Okuma"))
        self.CbSpor.setText(_translate("MainWindow", "Spor"))
        self.grouDersler.setTitle(_translate("MainWindow", "GroupBox"))
        self.CbWebTasarm.setText(_translate("MainWindow", "Web Tasarım"))
        self.CbProgramlama.setText(_translate("MainWindow", "Programlama"))
        self.CbMatematik.setText(_translate("MainWindow", "Matematik"))
        self.btn_result_Ders.setText(_translate("MainWindow", "Dersleri Onayla"))
        self.menuChekingg.setTitle(_translate("MainWindow", "Chekingg"))
