# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ComboBoxCitys.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(496, 319)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.CbBox = QtWidgets.QComboBox(self.centralwidget)
        self.CbBox.setGeometry(QtCore.QRect(60, 20, 271, 51))
        self.CbBox.setObjectName("CbBox")
        self.lbl_one = QtWidgets.QLabel(self.centralwidget)
        self.lbl_one.setGeometry(QtCore.QRect(360, 30, 101, 31))
        self.lbl_one.setObjectName("lbl_one")
        self.btnGetItem = QtWidgets.QPushButton(self.centralwidget)
        self.btnGetItem.setGeometry(QtCore.QRect(30, 90, 211, 71))
        self.btnGetItem.setObjectName("btnGetItem")
        self.btnLoadItem = QtWidgets.QPushButton(self.centralwidget)
        self.btnLoadItem.setGeometry(QtCore.QRect(260, 90, 211, 71))
        self.btnLoadItem.setObjectName("btnLoadItem")
        self.btnClearItems = QtWidgets.QPushButton(self.centralwidget)
        self.btnClearItems.setGeometry(QtCore.QRect(150, 190, 211, 71))
        self.btnClearItems.setObjectName("btnClearItems")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 496, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_one.setText(_translate("MainWindow", ": ✔"))
        self.btnGetItem.setText(_translate("MainWindow", "Get Item"))
        self.btnLoadItem.setText(_translate("MainWindow", "Load Items"))
        self.btnClearItems.setText(_translate("MainWindow", "Clear Items"))
