# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'listing.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(590, 411)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listItems = QtWidgets.QListWidget(self.centralwidget)
        self.listItems.setGeometry(QtCore.QRect(40, 20, 256, 331))
        self.listItems.setObjectName("listItems")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(340, 20, 201, 331))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Buton_Add = QtWidgets.QPushButton(self.widget)
        self.Buton_Add.setObjectName("Buton_Add")
        self.verticalLayout.addWidget(self.Buton_Add)
        self.Buton_Edit = QtWidgets.QPushButton(self.widget)
        self.Buton_Edit.setObjectName("Buton_Edit")
        self.verticalLayout.addWidget(self.Buton_Edit)
        self.Buton_Remove = QtWidgets.QPushButton(self.widget)
        self.Buton_Remove.setObjectName("Buton_Remove")
        self.verticalLayout.addWidget(self.Buton_Remove)
        self.Buton_Up = QtWidgets.QPushButton(self.widget)
        self.Buton_Up.setObjectName("Buton_Up")
        self.verticalLayout.addWidget(self.Buton_Up)
        self.Buton_Down = QtWidgets.QPushButton(self.widget)
        self.Buton_Down.setObjectName("Buton_Down")
        self.verticalLayout.addWidget(self.Buton_Down)
        self.Buton_Sort = QtWidgets.QPushButton(self.widget)
        self.Buton_Sort.setObjectName("Buton_Sort")
        self.verticalLayout.addWidget(self.Buton_Sort)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.Buton_Exit = QtWidgets.QPushButton(self.widget)
        self.Buton_Exit.setObjectName("Buton_Exit")
        self.verticalLayout.addWidget(self.Buton_Exit)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 590, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Buton_Add.setText(_translate("MainWindow", "Add"))
        self.Buton_Edit.setText(_translate("MainWindow", "Edit"))
        self.Buton_Remove.setText(_translate("MainWindow", "Remove"))
        self.Buton_Up.setText(_translate("MainWindow", "Up"))
        self.Buton_Down.setText(_translate("MainWindow", "Down"))
        self.Buton_Sort.setText(_translate("MainWindow", "Sort"))
        self.Buton_Exit.setText(_translate("MainWindow", "Exit"))
