# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Table.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(514, 522)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.TableProducts = QtWidgets.QTableWidget(self.centralwidget)
        self.TableProducts.setGeometry(QtCore.QRect(40, 30, 261, 241))
        self.TableProducts.setObjectName("TableProducts")
        self.TableProducts.setColumnCount(0)
        self.TableProducts.setRowCount(0)
        self.Onayla = QtWidgets.QPushButton(self.centralwidget)
        self.Onayla.setGeometry(QtCore.QRect(360, 410, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        self.Onayla.setFont(font)
        self.Onayla.setObjectName("Onayla")
        self.EditName = QtWidgets.QLineEdit(self.centralwidget)
        self.EditName.setGeometry(QtCore.QRect(350, 350, 113, 20))
        self.EditName.setObjectName("EditName")
        self.EditPrice = QtWidgets.QLineEdit(self.centralwidget)
        self.EditPrice.setGeometry(QtCore.QRect(350, 380, 113, 20))
        self.EditPrice.setObjectName("EditPrice")
        self.lbl_Name = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Name.setGeometry(QtCore.QRect(300, 350, 41, 16))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        self.lbl_Name.setFont(font)
        self.lbl_Name.setObjectName("lbl_Name")
        self.lbl_price = QtWidgets.QLabel(self.centralwidget)
        self.lbl_price.setGeometry(QtCore.QRect(300, 380, 41, 16))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        self.lbl_price.setFont(font)
        self.lbl_price.setObjectName("lbl_price")
        self.lbl_urun = QtWidgets.QLabel(self.centralwidget)
        self.lbl_urun.setGeometry(QtCore.QRect(370, 320, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        self.lbl_urun.setFont(font)
        self.lbl_urun.setObjectName("lbl_urun")
        self.lbl_Durum = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Durum.setGeometry(QtCore.QRect(300, 440, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        self.lbl_Durum.setFont(font)
        self.lbl_Durum.setObjectName("lbl_Durum")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 514, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Onayla.setText(_translate("MainWindow", "Onayla"))
        self.lbl_Name.setText(_translate("MainWindow", "Name:"))
        self.lbl_price.setText(_translate("MainWindow", "Price:"))
        self.lbl_urun.setText(_translate("MainWindow", "Ürün Ekleme"))
        self.lbl_Durum.setText(_translate("MainWindow", " Durum ❓ : Girilmedi"))
